# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: server.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='server.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cserver.proto\"\x1b\n\x0bTextRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x19\n\tTextReply\x12\x0c\n\x04text\x18\x01 \x01(\t2y\n\nOCR_Server\x12#\n\x05Print\x12\x0c.TextRequest\x1a\n.TextReply\"\x00\x12\"\n\x04Load\x12\x0c.TextRequest\x1a\n.TextReply\"\x00\x12\"\n\x04Scan\x12\x0c.TextRequest\x1a\n.TextReply\"\x00\x62\x06proto3'
)




_TEXTREQUEST = _descriptor.Descriptor(
  name='TextRequest',
  full_name='TextRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='TextRequest.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=43,
)


_TEXTREPLY = _descriptor.Descriptor(
  name='TextReply',
  full_name='TextReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='TextReply.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=45,
  serialized_end=70,
)

DESCRIPTOR.message_types_by_name['TextRequest'] = _TEXTREQUEST
DESCRIPTOR.message_types_by_name['TextReply'] = _TEXTREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TextRequest = _reflection.GeneratedProtocolMessageType('TextRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEXTREQUEST,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:TextRequest)
  })
_sym_db.RegisterMessage(TextRequest)

TextReply = _reflection.GeneratedProtocolMessageType('TextReply', (_message.Message,), {
  'DESCRIPTOR' : _TEXTREPLY,
  '__module__' : 'server_pb2'
  # @@protoc_insertion_point(class_scope:TextReply)
  })
_sym_db.RegisterMessage(TextReply)



_OCR_SERVER = _descriptor.ServiceDescriptor(
  name='OCR_Server',
  full_name='OCR_Server',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=72,
  serialized_end=193,
  methods=[
  _descriptor.MethodDescriptor(
    name='Print',
    full_name='OCR_Server.Print',
    index=0,
    containing_service=None,
    input_type=_TEXTREQUEST,
    output_type=_TEXTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Load',
    full_name='OCR_Server.Load',
    index=1,
    containing_service=None,
    input_type=_TEXTREQUEST,
    output_type=_TEXTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Scan',
    full_name='OCR_Server.Scan',
    index=2,
    containing_service=None,
    input_type=_TEXTREQUEST,
    output_type=_TEXTREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OCR_SERVER)

DESCRIPTOR.services_by_name['OCR_Server'] = _OCR_SERVER

# @@protoc_insertion_point(module_scope)
