# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import server_pb2 as server__pb2


class OCR_ServerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Print = channel.unary_unary(
                '/OCR_Server/Print',
                request_serializer=server__pb2.TextRequest.SerializeToString,
                response_deserializer=server__pb2.TextReply.FromString,
                )
        self.Load = channel.unary_unary(
                '/OCR_Server/Load',
                request_serializer=server__pb2.TextRequest.SerializeToString,
                response_deserializer=server__pb2.TextReply.FromString,
                )


class OCR_ServerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Print(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Load(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OCR_ServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Print': grpc.unary_unary_rpc_method_handler(
                    servicer.Print,
                    request_deserializer=server__pb2.TextRequest.FromString,
                    response_serializer=server__pb2.TextReply.SerializeToString,
            ),
            'Load': grpc.unary_unary_rpc_method_handler(
                    servicer.Load,
                    request_deserializer=server__pb2.TextRequest.FromString,
                    response_serializer=server__pb2.TextReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'OCR_Server', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OCR_Server(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Print(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/OCR_Server/Print',
            server__pb2.TextRequest.SerializeToString,
            server__pb2.TextReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Load(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/OCR_Server/Load',
            server__pb2.TextRequest.SerializeToString,
            server__pb2.TextReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
