# if you got any error when building this, just run snapcraft build --debug
# then delete the whole folder of flutter_ocr under parts folder
name: flutter-ocr
version: '1.0'
summary: Let's release the OCR power of Python with the support of flutter.
description: This is an app to help you convert image to text by using Deep Learning OCR techs.

confinement: strict
base: core18

parts:
  yingshaoxo-ocr:
    plugin: python
    python-version: python3
    source: .
    #python-packages: [easyocr]
    #
    #easyocr:
    #  plugin: python
    #  python-version: python3
    #  source: https://github.com/JaidedAI/EasyOCR.git
    #  stage-packages:
    #    - python-six
  flutter-ocr:
    plugin: flutter
    #source: https://github.com/yingshaoxo/flutter-ocr.git
    source: .
    flutter-target: lib/main.dart

slots:
  dbus-flutter-ocr:
    interface: dbus
    bus: session
    name: com.example.flutter_ocr

apps:
  yingshaoxo-ocr:
    command: usr/bin/python3 $SNAP/bin/ocr_server
  flutter-ocr:
    command: bin/flutter_ocr
    extensions: [flutter-dev]
    slots:
      - dbus-flutter-ocr
