# if you got any error when building this, just run snapcraft --debug
# then delete the whole folder of flutter_ocr under parts folder
#
#sudo systemctl stop snap.multipass.multipassd.service
#sudo vim /var/snap/multipass/common/data/multipassd/multipassd-vm-instances.json
#sudo systemctl start snap.multipass.multipassd.service
#
name: flutter-ocr
version: '1.0'
summary: Let's release the OCR power of Python with the support of flutter.
description: This is an app to help you convert image to text by using Deep Learning OCR techs.

confinement: strict
base: core18

architectures:
- build-on: amd64

parts:
  yingshaoxo-ocr:
    plugin: python
    python-version: python3
    source: .
    python-packages: [torch, opencv-python, scipy, numpy, Pillow, scikit-image, python-bidi, easyocr, grpcio, protobuf, auto_everything]
    stage-packages:
      - libgomp1
        #build-packages:
        #  - libcrystalhd-dev
        #  - nvidia-cuda-dev
        #  - nvidia-cuda-toolkit
  flutter-ocr:
    plugin: flutter
    #source: https://github.com/yingshaoxo/flutter-ocr.git
    source: .
    flutter-target: lib/main.dart

slots:
  dbus-flutter-ocr:
    interface: dbus
    bus: session
    name: com.example.flutter_ocr

apps:
  flutter-ocr:
    command: usr/bin/python3 $SNAP/bin/ocr_server.py
    extensions: [flutter-dev]
    slots:
      - dbus-flutter-ocr

plugs:
  desktop:
  desktop-legacy:
  x11:
  unity7:
  wayland:
  opengl:
  home:
  process-control:
  network-bind:
  network:
