name: flutter-ocr
version: '1.0'
summary: Let's release the OCR power of Python with the support of flutter.
description: This is an app to help you convert image to text by using Deep Learning OCR techs.

confinement: strict
base: core18

parts:
  flutter-ocr:
    plugin: flutter
    source: https://github.com/yingshaoxo/flutter-ocr
    flutter-target: lib/main.dart

apps:
  flutter-ocr:
    command: flutter-ocr
    extensions: [flutter-dev]
